name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Login DockerHub
      run: 
        sudo docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    - name: Build the Docker image
      run:     
        sudo docker build -t "$DOCKER_USERNAME"/sara-chatbot:$(date +%s) ./app
