name: Server GPU CI/CD

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'server_gpu/**'
  pull_request:
    branches: 
      - 'main'

jobs:
  copy_remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete remote content
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USERNAME }}
        pass: ${{ secrets.SSH_PASSWORD }}
        run: |
          rm -r /mnt/homeGPU/${{ secrets.SSH_USERNAME }}/server_gpu
    - name: Copy content
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "./server_gpu"
        target: /mnt/homeGPU/${{ secrets.SSH_USERNAME }}/aux

